const TestData = [
  ["One", "Un", 1],
  ["Two", "Deux", 1],
  ["Three", "Trois", 1],
  ["Four", "Quatre", 1],
  ["Five", "Cinq", 1],
  ["Six", "Six", 1],
  ["Seven", "Sept", 1],
  ["Eight", "Huit", 1],
  ["Nine", "Neuf", 1],
  ["Ten", "Dix", 1],
  ["Blue", "Bleu", 2],
  ["Red", "Rouge", 2],
  ["Yellow", "Jaune", 2],
  ["Green", "Vert", 2],
  ["Pink", "Rose", 2],
  ["Black", "Noir", 2],
  ["White", "Blanc", 2],
  ["Brown", "Marron", 2],
  ["Grey", "Gris", 2],
  ["Grape", "du raisin", 3],
  ["Orange", "une orange", 3],
  ["Apple", "une pomme", 3],
  ["Strawberry", "une fraise", 3],
  ["Banana", "une banana", 3],
  ["Lemon", "un citron", 3],
  ["Mango", "une mangue", 3],
  ["Pear", "une poire", 3],
];
export default TestData;
